# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='isvip',
        ),
        migrations.AddField(
            model_name='film',
            name='is_vip',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='sub_class_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
